### ISSUE TITLE
Hello World?

### ISSUE THREAD

**Issue by seanquijote** [saavedrajb/saavedrajb.github.io#1]
`Hello World?`

**Comment by seanquijote** [comment]
Pls fix

**Comment by saavedrajb** [comment]
Only GOD Prince can fix the world, I bet he has github too.

**Comment by seanquijote** [comment]
# Both you and [him](https://github.com/princeandrewdiana) are gonna fix the world?

**Comment by saavedrajb** [comment]
Only him tho.
